baseurl: "https://rayxi.top"
languageCode: en-us
theme: hugo-theme-stack
paginate: 7
title: Ruixi-rebirth

# Change it to your Disqus shortname before using
disqusShortname: ruixi

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: zh-cn

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

permalinks:
  post: "/p/:slug/"
  page: "/:slug/"

params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon: "/img/favicon.ico"

  footer:
    since: 2021
    customText:  Ruixi-rebirth’s Blog

  dateFormat:
    published: "Jan 02, 2006"
    lastUpdated: "Jan 02, 2006 15:04 MST"

  sidebar:
    emoji: 
    subtitle: 「 井底之蛙 不知大海之宽阔 却知晓天空之蓝 」
    avatar:
      enabled: true
      local: true
      src: "/img/avatar.jpg"
    # twitter:
    #   username: ruixi_rebirth
    # email:
    #   email: ruixirebirth@gmail.com
    github:
      username: Ruixi-rebirth
    # telegram:
    #   username: Ruixi_rebirth
    gpg:
      url: https://github.com/ruixi-rebirth.gpg
    rss:
      enabled: true
    # bilibili:
    #   UID: 362142672

  article:
    math: true
    toc: true
    license:
      enabled: false
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    enabled: true
    provider: utterances
    utterances:
      repo: Ruixi-rebirth/Ruixi-rebirth.github.io
      # issueTerm: 必填项，issue标题的切分规则，可写 pathname title url
      issueTerm: pathname
      theme: dark-blue 
      label: comment

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 15
      - type: categories
        params:
          limit: 15
      - type: tag-cloud
        params:
          limit: 25
    page:
        - type: toc

  friends:
    friend:
      - name: 艾雨寒 | 艾颖初 初等记忆体
        url: "https://axionl.me/"
        avatar: "https://avatars1.githubusercontent.com/u/8396456"
        desc: 
      - name: Lilydjwg
        url: "https://blog.lilydjwg.me"
        avatar: "https://avatars1.githubusercontent.com/u/440661"
        desc: 
      - name: Farseerfc
        url: "https://farseerfc.me"
        avatar: "https://farseerfc.me/images/avatar.jpg"
        desc: 
      - name: Zjuyk
        url: "https://zjuyk.site"
        avatar: "https://avatars2.githubusercontent.com/u/76436317"
        desc: 玄机洞天
      - name: 李皓奇
        url: "https://liolok.com/zhs/"
        avatar: "https://avatars.githubusercontent.com/u/34574198"
        desc: 
      - name: CSSLayer
        url: "https://www.csslayer.info/"
        avatar: "https://avatars.githubusercontent.com/u/259684"
        desc: "老 K，fcitx* 系列开发者"
        
  opengraph:
    twitter:
      # Your Twitter username
      site: ruixi_rebirth

      # Available values: summary, summary_large_image
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: true
      local: true
      src: img/default.jpg

  colorScheme:
    # Display toggle
    toggle: true

    # Available values: auto, light, dark
    default: dark

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true
  banner:
    info: 朝生，暮死。众生皆如此，可否不辜负?
    local:
      enabled: true
      url: "https://zh.moegirl.org.cn/index.php?title=%E7%99%BE%E5%A6%96%E8%B0%B1&variant=zh-hans&mobileaction=toggle_view_desktop"
      src: "/img/default.jpg"

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
  main:
    - identifier: home
      name: 主页
      url: /
      weight: -100
      pre: home
    - identifier: friends
      name: 友链
      url: friends
      weight: -90
      pre: friends
    - identifier: about
      name: 关于
      url: about
      weight: -80
      pre: user
    - identifier: archives
      name: 归档
      url: archives
      weight: -70
      pre: archives
    - identifier: search
      name: 搜索
      url: search
      weight: -60
      pre: search

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200
markup:
  goldmark:
    renderer:
      unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
